<?php
require '../../../connect.php';
require '../../../user.php';
$candidateid=$_SESSION['candidateid'];
$userrole=$_SESSION['userrole'];
$enquiry_id=$_REQUEST['id'];
/* $cosel=$con->query("select * from cost_sheet_entry where status=3 and  created_by='$candidateid' limit 1" );
$cofet=$cosel->fetch();
$costno=$cofet['cost_sheet_no']; */
  
?>
<head>
    <link rel="stylesheet" href="Qvision\commonstyle.css">
    </head>
<style>
	.card-primary:not(.card-outline)>.card-header{
		background-color: #f1cc61 !important;
	}
	</style>
<div class="card card-primary">
  
	<div class="card-header"><h3 class="card-title"><font size="5">PO UPLOAD LIST</font></h3></div>
    <div class="card-body"style="overflow-x:scroll;">
    <table class="table table-striped table-bordered table-hover display nowrap"  id="example1" style="width:100%">
    <thead>
		<th>Id</th>
		<th>Quote No</th>
		<th>Cost Sheet No</th>		
		<th>PO Upload</th>   
		<th>Status</th>
		<th>Action</th>

      <!--th>Tools</th-->
      </thead>
      <tbody>
      <?php
	  
	 
	  
	  $emp_sql=$con->query("SELECT distinct a.cost_sheet_no,a.approved_by,a.status as cs_status,b.quote_no as qquote,b.*,c.id as enq_id,c.created_by FROM cost_sheet_entry a left join quote_generate b on (a.cost_sheet_no=b.cost_sheet_no) left join enquiry c on (a.enquiry_id=c.id)where a.status=3 and c.id='$enquiry_id' and a.edit_status=0 group by a.cost_sheet_no" );
	  

      $cnt=1;
      while($emp_res = $emp_sql->fetch(PDO::FETCH_ASSOC))
      {
		$approved_id = $emp_res['created_by'];
		//echo$qquote = $emp_res['qquote'];
		$stmt = $con->prepare("SELECT emp_name from staff_master where candid_id ='$approved_id' "); 	
		 //echo "SELECT emp_name from staff_master where candid_id ='$approved_id'";
		 $stmt->execute(); 
		 $row = $stmt->fetch();
		 $emp_name = $row['emp_name'];
       ?>
      <tr>
      <td><?php echo $cnt; ?>.</td>
	        <td><?php echo $emp_res['qquote']; ?></td>
            <td><?php echo $emp_res['cost_sheet_no']; ?></td>	 
	        <td><?php echo $emp_res['po']; ?></td>
       <td>
	   <?php  if($emp_res['cs_status']==3){  echo '<span style="color:green;text-align:center;"><b>Quote Generated By - ' ;?>
	   <?php echo $emp_name;?>/<?php echo '<span style="color:green;"><b>Quote Sended </b></span>';
	   echo '<span style="color:green;"><b> & </b></span>';
	   echo '<span style="color:red;"><b>Waiting for PO Upload</b></span>'; } ?>         
	   </td>
		<td>
	     <button class="btn btn-info" data-id="<?php echo $emp_res['id']; ?>" onclick="po_upload_view(<?php echo $emp_res['id']; ?>)">
	     <i class="fa fa-eye"></i></button>
	    </td>
      
      </tr>
      <?php
	  $cnt=$cnt+1;
      }
      ?>
       </tbody>
      </table>
    </div>
<!-- /.content -->
</div>
<script>
function po_upload_view(v){
	  //alert(v);
	$.ajax({
	type:"POST",
	url:"qvision/BusinessProcess/po_approval/po_upload_view.php?id="+v,
	success:function(data)
	{
		$("#main_content").html(data);
	}
	})
}
</script>
<script>
$(document).ready(function() {
    $('#example1').DataTable( {
        "scrollX": true
    } );
} );
</script>
<script>
		

$(function () {
  //   $("#example1").DataTable({
  //     "responsive": true,
  //     "autoWidth": false,
  //   });
  //   $('#example2').DataTable({
  //     "paging": true,
  //     "lengthChange": false,
  //     "searching": false,
  //     "ordering": true,
  //     "info": true,
  //     "autoWidth": false,
  //     "responsive": true,
  //   });
  // });

</script>